name: Runtimer lets you bake a custom JRE on GH Actions

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      java-version:
        description: 'JVM version'
        required: false
        type: string
        default: '11'
      java-distribution:
        description: 'JVM distribution'
        required: false
        type: string
        default: 'temurin'
      java-modules:
        description: 'Java Modules'
        required: false
        type: string
        default: 'java.base,java.logging,java.naming,java.xml,java.sql,java.transaction.xa,java.security.sasl,java.management'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version  }}

      - name: Run jlink
        run: jlink --output ${{ matrix.os }}/ --add-modules ${{ inputs.java-modules }}

      - name: Zip artifact on linux/macos
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: zip -r ${{ matrix.os }}-jre.zip ${{ matrix.os }}

      - name: Zip artifact on win
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: 7z a -tzip ${{ matrix.os }}-jre.zip ${{ matrix.os }}\

      - name: Archive for transfer to draft_release job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-jre
          path: ${{ matrix.os }}-jre.zip
